name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.3.0
homepage: https://pinchbv.github.io/floor/
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor_annotation:
    git:
      url: https://github.com/idozo/my_floor.git
      path: floor_annotation
      ref: feature/support_dart_core_type_in_dao
      
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.1
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.2
  collection: ^1.15.0
  
  floor_annotation:
    git:
      url: https://github.com/idozo/my_floor.git
      path: floor_generator
      ref: feature/support_dart_core_type_in_dao
   
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.15
